/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Mensajes;

/**
 *
 * @author anton
 */
public class Informacion extends javax.swing.JDialog {

    /**
     * Creates new form Informacion
     */
    public Informacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Configurar el tamaño de la ventana
        setSize(760, 800);

        // Centrar la ventana en la pantalla
        setLocationRelativeTo(null);
    }

//    Informacion() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("TUTORIA  EN EL IESTP “ CARLOS SALZAR ROMERO”");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 420, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(22);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("  \n  LA TUTORIA ES UNA DE LAS ACTIVIDADES  QUE REALIZAN NUESTROS \n  DOCENTES Y ES RECONOCIDA ESTA LOABLE LABOR.\n\n  LA TUTORIA ES EL ACOMPAÑAMIENTO PERMANENTE \n  QUE REALIZA EL DOCENTE A SUS ALUMNOS,DESDE QUE ESTOS\n  INGRESAN HASTA QUE EGRESAN(MINEDU).\n\n  CADA UNO DE NUESTROS  OCHO PROGRAMAS ACADEMICOS \n  DESIGNAN A SUS DOCENTES TUTORES Y ESTOS PUBLICAN \n  SUS NHORARIOS DE ATENCIÓN EN SUS VITRINAS Y EN LOS MEDIOS \n  DIGITALES DISPONIBLES.\n\n  LA ATENCIÓN TUTORIAL PUEDE SER INDIVIDUAL Y/O GRUPAL\n\n  LOS TUTORES ESTAN OBLIGADOS A REGISTRAR E INFORMAR LA A\n  TENCIÓN QUE LLEVAN A CABO, PRIMERO AL COORDINADOR Y LUEGO\n  AL RESPONSABLE DEL PROGRAMA A NIVEL INSTITUCIONAL CUYA SEDE\n  ES LA UNIDAD DE BIENESTAR.\n\n        ¿CUALES SON LOS BENEFICIOS DEL REGISTRO Y LA ATENCIÓN TUTORIAL?\n\n  1.A la Institución nos ayuda a conocer las causas por las cuales \n     nuestros alumnos: FALTAN, RINDEN POR DEBAJO DE LA MEDIA,DESERTAN O \n     ABANDONAN LOS ESTUDIOS,POR SALUD,POR TRABAJO,PROBLEMAS \n     FAMILIARES,ETC.\n  2.Los jefes o coordinadores de programa se reúnen conjuntamente \n     con el jefe de la unidad académica para evaluar y tomar decisiones \n     que redunden en beneficio de la buena marcha académica de nuestros alumnos.\n  3.Nos ayuda a diseñar programas preventivos y mejorar la calidad del servicio educativo.\n  4.Permitirá que nuestras autoridades tomen las mejores decisiones y el prestigio \n     del Instituto se mantenga y acrecenté.\n\n  CON EL PROPÓSITO DE FACILITAR EL REGISTRO DE ATENCIÓN TUTORIAL,UN \n  EQUIPO DE DOCENTES Y ALUMNOS DISEÑAN UN PROGRAMA QUE DEBE PONER \n  A LA VANGUARDIA DE LA CALIDAD DEL SERVICIO EDUCATIVO Y QUE OTROS \n  INSTITUTOS DE LA REGIÓN Y EL PAÍS QUERRAN APLICAR.\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 670, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Informacion dialog = new Informacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
